### 1. Iniciar sesión para obtener Token JWT
# @name login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "prueba1@gmail.com",
  "password": "abc123"
}

### 2. Probar GET Mis Contactos (Nuestra Tarea 1)
GET http://localhost:5001/api/contactos/me
Authorization: Bearer {{login.response.body.token}}

### 3. Probar Alta de Contacto (Nuestra Tarea 1)
POST http://localhost:5001/api/contactos
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "usuarioContactoId": 2,
  "aliasPersonalizado": "Test IDE"
}

### 4. Crear Cuenta Origen propia con saldo de $50.000 (Tarea B4-BE)
# @name cuentaOrigen
POST http://localhost:5001/api/cuentas-billetera
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "billeteraId": 1,
  "alias": "Mi Brubank Franco",
  "saldoInicial": 50000.00
}

### 5. Crear Cuenta Destino propia con saldo de $10.000 (Tarea B4-BE)
# @name cuentaDestino
POST http://localhost:5001/api/cuentas-billetera
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "billeteraId": 2,
  "alias": "Mi Mercado Pago Franco",
  "saldoInicial": 10000.00
}

### 6. Probar Envio con Doble Movimiento (Nuestra Tarea 2)
POST http://localhost:5001/api/operaciones/enviar
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "cuentaOrigenId": {{cuentaOrigen.response.body.cuentaBilleteraId}},
  "categoriaId": 5,
  "monto": 500.00,
  "descripcion": "Pago de cena al grupo",
  "cuentaDestinoId": {{cuentaDestino.response.body.cuentaBilleteraId}}
}