// <auto-generated />
using System;
using Billeteras.DatosEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Billeteras.DatosEF.Migrations
{
    [DbContext(typeof(BilleterasContext))]
    [Migration("20260627181205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Billeteras.Entidades.Billetera", b =>
                {
                    b.Property<int>("BilleteraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BilleteraId"));

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BilleteraId");

                    b.ToTable("Billetera");
                });

            modelBuilder.Entity("Billeteras.Entidades.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Billeteras.Entidades.Comercio", b =>
                {
                    b.Property<int>("ComercioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComercioId"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ComercioId");

                    b.ToTable("Comercio");
                });

            modelBuilder.Entity("Billeteras.Entidades.ComercioBilletera", b =>
                {
                    b.Property<int>("ComercioId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("TasaComision")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComercioId", "BilleteraId");

                    b.ToTable("ComercioBilletera");
                });

            modelBuilder.Entity("Billeteras.Entidades.Contacto", b =>
                {
                    b.Property<int>("UsuarioPropietarioId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("UsuarioContactoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("AliasPersonalizado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioPropietarioId", "UsuarioContactoId");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("Billeteras.Entidades.CuentaBilletera", b =>
                {
                    b.Property<int>("CuentaBilleteraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuentaBilleteraId"));

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CuentaBilleteraId");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CuentaBilletera", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Billeteras.Entidades.MetodoPagoExterno", b =>
                {
                    b.Property<int>("MetodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoId"));

                    b.Property<string>("EntidadEmisora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UltimosCuatro")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MetodoId");

                    b.ToTable("MetodoPagoExterno");
                });

            modelBuilder.Entity("Billeteras.Entidades.MotivoReporte", b =>
                {
                    b.Property<int>("MotivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotivoId"));

                    b.Property<int>("Gravedad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MotivoId");

                    b.ToTable("MotivoReporte");
                });

            modelBuilder.Entity("Billeteras.Entidades.Movimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaBilleteraId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataExtranjera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MovimientoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuentaBilleteraId");

                    b.ToTable("Movimiento");
                });

            modelBuilder.Entity("Billeteras.Entidades.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionId");

                    b.ToTable("Notificacion");
                });

            modelBuilder.Entity("Billeteras.Entidades.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Billeteras.Entidades.SolicitudCobro", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioSolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId");

                    b.HasIndex("UsuarioSolicitanteId");

                    b.ToTable("SolicitudCobro");
                });

            modelBuilder.Entity("Billeteras.Entidades.SolicitudCobroDetalle", b =>
                {
                    b.Property<int>("DetalleSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleSolicitudId"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("MontoMita")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MovimientoId")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioDeudorId")
                        .HasColumnType("int");

                    b.HasKey("DetalleSolicitudId");

                    b.HasIndex("MovimientoId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioDeudorId");

                    b.ToTable("SolicitudCobroDetalle");
                });

            modelBuilder.Entity("Billeteras.Entidades.Sucursal", b =>
                {
                    b.Property<int>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SucursalId"));

                    b.Property<string>("CodigoQRBase")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ComercioId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SucursalId");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketAdjunto", b =>
                {
                    b.Property<int>("AdjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdjuntoId"));

                    b.Property<int>("MensajeId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AdjuntoId");

                    b.HasIndex("MensajeId");

                    b.ToTable("TicketAdjunto");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketMensaje", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensajeId"));

                    b.Property<string>("CuerpoMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RemitenteEsSoporte")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("MensajeId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMensaje");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketSoporte", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MotivoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("MotivoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TicketSoporte");
                });

            modelBuilder.Entity("Billeteras.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Billeteras.Entidades.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UsuarioId", "RolId");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("Billeteras.Entidades.CuentaBilletera", b =>
                {
                    b.HasOne("Billeteras.Entidades.Billetera", "Billetera")
                        .WithMany()
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billeteras.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billetera");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Billeteras.Entidades.Movimiento", b =>
                {
                    b.HasOne("Billeteras.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billeteras.Entidades.CuentaBilletera", "CuentaBilletera")
                        .WithMany()
                        .HasForeignKey("CuentaBilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("CuentaBilletera");
                });

            modelBuilder.Entity("Billeteras.Entidades.SolicitudCobro", b =>
                {
                    b.HasOne("Billeteras.Entidades.Usuario", "UsuarioSolicitante")
                        .WithMany()
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("Billeteras.Entidades.SolicitudCobroDetalle", b =>
                {
                    b.HasOne("Billeteras.Entidades.Movimiento", "Movimiento")
                        .WithMany()
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Billeteras.Entidades.SolicitudCobro", "Solicitud")
                        .WithMany("Lineas")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billeteras.Entidades.Usuario", "UsuarioDeudor")
                        .WithMany()
                        .HasForeignKey("UsuarioDeudorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movimiento");

                    b.Navigation("Solicitud");

                    b.Navigation("UsuarioDeudor");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketAdjunto", b =>
                {
                    b.HasOne("Billeteras.Entidades.TicketMensaje", "Mensaje")
                        .WithMany("Adjuntos")
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketMensaje", b =>
                {
                    b.HasOne("Billeteras.Entidades.TicketSoporte", "Ticket")
                        .WithMany("Mensajes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketSoporte", b =>
                {
                    b.HasOne("Billeteras.Entidades.MotivoReporte", "Motivo")
                        .WithMany()
                        .HasForeignKey("MotivoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Billeteras.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Motivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Billeteras.Entidades.SolicitudCobro", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketMensaje", b =>
                {
                    b.Navigation("Adjuntos");
                });

            modelBuilder.Entity("Billeteras.Entidades.TicketSoporte", b =>
                {
                    b.Navigation("Mensajes");
                });
#pragma warning restore 612, 618
        }
    }
}
